### ISSUE TITLE
Problem with instalation

### ISSUE THREAD

**Issue by DariaSereb** [ppgee/cocos-pnp#10]
Hi, currently trying to use your plugin, at all version of Cocos I'm getting this kind of error, can you help me please, I'm new to Cocos and possibly doing something wrong.
![screen](https://github.com/ppgee/cocos-pnp/assets/23449296/723f34d0-0a37-4b84-babd-35aa8e0a6c48)

**Comment by ppgee** [comment]
You can find [the release package](https://github.com/ppgee/cocos-pnp/releases/tag/playable-ads-adapter-1.3.5) and download to use.

**Comment by DariaSereb** [comment]
Thank you for the reply, I tried new release and I get the same error, possibly I'm doing something wrong. I tried to install through extension manger, and I also tried just copy the plaugine folder to extension folder. Maybe I need to install some external library?

**Comment by ppgee** [comment]
Is your plugin placed like this? Please refer to this image: 

<img width="341" alt="image" src="https://github.com/ppgee/cocos-pnp/assets/9589562/1ed8f336-0458-49de-8c3d-f346cc47c30c">

**Comment by DariaSereb** [comment]
Thank you, it worked. Can I ask, do you have a .adapterrc file with Mintegral configuration? I tried to follow their guidelines from a playable preview tool, but  any of my test projects came through their test tool

**Comment by ppgee** [comment]
The provided methods need to be called correctly; methods such as gameXXX just need to be called at the right moment.
Or you could specify exactly what is not passing.

**Comment by DariaSereb** [comment]
I have problem with Call to download and gameEnd method, I tried call them in different moments, but with no success.

**Comment by ppgee** [comment]
<img width="936" alt="image" src="https://github.com/ppgee/cocos-pnp/assets/9589562/bdb7ecec-ebbb-4b38-9335-90771621bd40">
<img width="313" alt="image" src="https://github.com/ppgee/cocos-pnp/assets/9589562/3563b767-cfe1-4982-b1e9-7abd7eeefab7">
<img width="332" alt="image" src="https://github.com/ppgee/cocos-pnp/assets/9589562/0a4f2b2b-b70c-433d-bc32-a4eec9574722">

I check again and it was passed. Did you have any problems with call methods?
