### ISSUE TITLE
enableSplash does not work

### ISSUE THREAD

**Issue by kidcry0x** [ppgee/cocos-pnp#11]
- **Cocos Creator version:** 3.6.3, 3.7.4, 3.8.2 (I tested all 3 versions and got errors)
- **cocos-pnp version:** 1.3.7
- I want to remove the default loading screen of Cocos. In the _**.adapterrc**_ I have changed the **enableSplash** attribute to **false**. But after the build is completed, Cocos' default loading screen is still there and has not been deleted.
- 
![image](https://github.com/ppgee/cocos-pnp/assets/61981331/7d254fc6-7597-41cb-a8bf-73c614adf57b)
![image](https://github.com/ppgee/cocos-pnp/assets/61981331/eebc60fe-76d9-4046-9643-9f0cdd694706)

**Comment by anhducne** [comment]
it works fine on 3.6.0, and it also cannot remove splash.

**Comment by kidcry0x** [comment]
> it works fine on 3.6.0, and it also cannot remove splash.

You mean version 3.6.0 can't remove loading screens either?

**Comment by ppgee** [comment]
oh, It has been confirmed as an issue, and I will fix it shortly.

In version 3.x.x, you can disable interstitials through build configuration.

<img width="590" alt="image" src="https://github.com/ppgee/cocos-pnp/assets/9589562/1054126a-fa51-4356-b745-9a2b3d0a5453">

**Comment by kidcry0x** [comment]
> In version 3.x.x, you can disable splash through build configuration.

It seems that disabling splash using build configuration is only supported from Cocos version 3.7.x and above

**Comment by kidcry0x** [comment]
> you can change the photo cocos logo as your avatar and adjust the background to black like this. https://www.mediafire.com/file/edbo1209oroxiai/index.html/file

Thank you, that's a great temporary fix.

**Comment by ppgee** [comment]
I was fixed it. Have a try.
