### ISSUE TITLE
Unity build for 382: Invalid url

### ISSUE THREAD

**Issue by Kodedyukh** [ppgee/cocos-pnp#20]
Hello!
I have problems compiling a 3.8.2 Cocos build with playable-ads-adapter 1.3.9 to the Unity ads network.
The core problem is that in the Unity testing [app](https://play.google.com/store/apps/details?id=com.unity3d.auicreativetestapp&hl=en) an invalid url is generated. See a screenshot below (screenshot is generated with JS log option turned on, in the the advanced tools section)
![AdTesting](https://github.com/ppgee/cocos-pnp/assets/18647961/ac808f0d-f7d2-4935-961c-2f470ceb0581)
 
At the same time, everything works fine when I run the build on localhost (python simpleHttp)
When I downgrade to Cocos 360 everything works fine in the Unity test app
Is there any way to fix this problem for 382 Cocos build?

Some additional thoughts:
Looks like the invalid url is generated when the build tries to create script out of the file in path “/web-mobile/cocos-js/meshopt_decoder.wasm-43855155.js”
And it seems like since Cocos 360 doesn’t generate this file everything goes fine in it

**Comment by Papirosnik** [comment]
I have a similair issue.
cocos 383 single index.html does not work in the Unity Ad Testing app.
It works elsewhere perfectly, even without any server - single index.html is able to load its resources from itself.
But Unity Ad Testing app refuses to show my ad.
Will try 360 now.
PS. Yes, with 360 works. @Kodedyukh thanks for this point!

PS2. Unfortunately, it works on android only. with ios it fails and shows some weird "downloads" labels at random places.

Upd 3. It started working on IOS as well, after replacing .webp images with .png; Still not working in End-Card mode...

Does anybody know how to postpone the start of the game (made with cocos-3.6.0) until video ad is ended?

**Comment by Kodedyukh** [comment]
@Papirosnik 
Maybe using cc.game.pause() can help, before isViewable became true inside mraid's "viewableChange" event's callback

**Comment by Kodedyukh** [comment]
With the last updates Cocos Creator 3.8.4  Unity build works out of the box

**Comment by Kodedyukh** [comment]
With the last updates Cocos Creator 3.8.4  Unity build works out of the box
