### ISSUE TITLE
.adapterrc 

### ISSUE THREAD

**Issue by anhducne** [ppgee/cocos-pnp#5]
I want to create my own templates for each network but I don't understand how to create " .adapterrc "  in the root folder is it the folder in the project or in the plugin can you guide me?

![image](https://github.com/ppgee/cocos-pnp/assets/68696607/c0aeb072-213f-4b40-8440-c475bb914dad)

**Comment by ppgee** [comment]
`.adapterrc`

just like: 

![demo](https://github.com/ppgee/cocos-pnp/assets/9589562/71490476-4cea-4ec9-8b18-c85094ff7088)

**Comment by anhducne** [comment]
![image](https://github.com/ppgee/cocos-pnp/assets/68696607/e1a54b36-7372-45ef-aefc-d4781bad8d6b)
So we won't need to add this line anymore bro?

**Comment by ppgee** [comment]
No, this is json file, `.adapterrc` is option.

`.adapterrc` is provided config If you need build with custom config.

**Comment by anhducne** [comment]
> No, this is json file, `.adapterrc` is option.
> 
> `.adapterrc` is provided config If you need build with custom config.

many thanks for you. this tool help me so much !
