### ISSUE TITLE
playable-adapter-core配置环境问题

### ISSUE THREAD

**Issue by w7131146** [ppgee/cocos-pnp#6]
您好，我下载了playable-adapter-core工程项目，但是项目无法运行启动，请问您的npm版本是多少？

**Comment by w7131146** [comment]
[!] RollupError: Node tried to load your configuration as an ES module even though it is likely CommonJS. To resolve this, change the extension of your configuration to ".cjs" or pass the "--bundleConfigAsCjs" flag.

Original error: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and 'K:\cocos-pnp-playable-ads-adapter-1.3.3\packages\playable-adapter-core\package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
https://rollupjs.org/command-line-interface/#bundleconfigascjs
ReferenceError: __dirname is not defined in ES module scope

**Comment by ppgee** [comment]
当前我的环境如下：
npm 版本为 8.19.4
node 版本为 16.20.0

**Comment by w7131146** [comment]
非常感谢您百忙之中的恢复，非常感谢。&nbsp;


六六
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "PGee ***@***.***&gt;; 
发送时间: 2023年7月31日(星期一) 晚上6:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ppgee/cocos-pnp] playable-adapter-core配置环境问题 (Issue #6)





 
当前我的环境如下：
 npm 版本为 8.19.4
 node 版本为 16.20.0
