### ISSUE TITLE
.adapterrc 文件应该放在哪个根目录下

### ISSUE THREAD

**Issue by Elikke-007** [ppgee/cocos-pnp#8]
作者你好！
我看了[https://github.com/ppgee/cocos-pnp/issues/5](url)，但还是存在疑问，下图是打包 cocos creator 扩展插件的源代码目录
![image](https://github.com/ppgee/cocos-pnp/assets/46101770/57f46d51-4610-4325-9a1c-874fb02ea95c)

我尝试将 .adapterrc 文件放在上图所示的根目录下，执行 playable-ads-adapter 目录下的 package.json 的指令 build:2x，
生成的扩展插件自动放在了 ~/.CocosCreator/packages 目录下，然后在 creator 编辑器中构建，但是打包结果跟我的配置不一致。
于是我尝试将 .adapterrc 文件放在 playable-ads-adapter 和 playable-adapter-core 下，分别执行其中打包指令，最后再构建，打包结果还是跟我的配置不一致。

也试过将 .adapterrc 文件放在 ~/.CocosCreator/packages/playable-ads-adapter/ 下，但也没有达到目的。

还试过在 .adapterrc 文件名后面添加后缀 .json，变成 .adapterrc.json，然后重复以上的操作，也是不行。

请问是我的操作错误吗？可以详细说明是怎么操作吗？
谢谢！感恩！！

我的 .adapterrc 文件代码如下：
```
{
    "buildPlatform": "web-mobile",
    "orientation": "auto",
    "enableSplash": true,
    "exportChannels": ["AppLovin","IronSource","Mintegral","Tiktok","Unity"],
    "injectOptions": {
        "Mintegral": {
            "body": "<script>window.gameStart=function(){}window.gameClose=function(){}</script>"
        },
        "Tiktok": {
            "body": "<script>window.openAppStore=function(){}</script>"
        }
    }
}
```

**Comment by ppgee** [comment]
`.adapterrc` 是放置在游戏项目根目录，这是插件 `playable-ads-adapter` 提供的能力，而非 `playable-adapter-core`

**Comment by Elikke-007** [comment]
谢谢大佬！
