### ISSUE TITLE
Not work in Facebook PlayableAds

### ISSUE THREAD

**Issue by KimihideIiizumi** [ppgee/cocos-pnp#9]
Hi, We use your nice library in CocosCreator3.6.1.

In this time, I made facebook playable ads, but can't play in [facebook playable preview](https://developers.facebook.com/tools/playable-preview/).

It only shows splashscreen and has a 2mb file size error.
However, my file size is not even 1mb.

I know these two problems are separate, but can you give me your opinion on each?

<img width="550" src="https://github.com/ppgee/cocos-pnp/assets/52649570/717f421c-c386-484f-b0e6-3f47f3903df8">
  
Thank you.

**Comment by ppgee** [comment]
Could you confirm that the built package can be run locally?

If the file is small than 1mb, you could set the config _isZip_ to false. (_isZip_ is true default)

**Comment by KimihideIiizumi** [comment]
I can confirm that the built package starts locally, nothing wrong with Applovin or Mintegral's Playable Preview.

And even if I remove isZip, the error is still there, although it does not reach 2mb.

**Comment by ppgee** [comment]
Does "not reach 2MB in size" refer to the size of each individual file or the overall size of the compressed folder? 
The potential issue at the moment is that if any file within the uncompressed folder exceeds 2MB, it may not pass the detection on Facebook.

**Comment by KimihideIiizumi** [comment]
It means that the individual file size before compression does not exceed 2 mb.

The error occurs even though I created a new project and built it with only the libraries included and none of them exceed 2mb.

Does it work fine in your environment?

**Comment by ppgee** [comment]
Try this new version of the plugin. I fixed it not long ago. [here](https://github.com/ppgee/cocos-pnp/releases/tag/playable-ads-adapter-1.3.6)

**Comment by KimihideIiizumi** [comment]
Thanks a lot, but the problem still seems to remain.

**Comment by ppgee** [comment]
I've tested it with the latest version, and it passes. Could you see if you need to further reduce or compress the project resources?

<img width="1006" alt="image" src="https://github.com/ppgee/cocos-pnp/assets/9589562/46a61e7a-1b20-4f3a-b2f3-a7ef10d85b77">

**Comment by KimihideIiizumi** [comment]
I see that it is working correctly in your environment.

It would be possible to pull out a few features, but I don't think further reduction of empty projects will solve the problem.
This is my build with an empty project, and this is causing 2mb errors.

[Facebook.zip](https://github.com/ppgee/cocos-pnp/files/14193423/Facebook.zip)

If you don't mind, could you try to see if this build also causes problems with your previewtool?
this build used the latest libraries you have prepared.

**Comment by ppgee** [comment]
It works.
<img width="1000" alt="image" src="https://github.com/ppgee/cocos-pnp/assets/9589562/7f0ca8c8-2ce4-4f16-9d9e-d07b76a45caa">


> I see that it is working correctly in your environment.
> 
> It would be possible to pull out a few features, but I don't think further reduction of empty projects will solve the problem. This is my build with an empty project, and this is causing 2mb errors.
> 
> [Facebook.zip](https://github.com/ppgee/cocos-pnp/files/14193423/Facebook.zip)
> 
> If you don't mind, could you try to see if this build also causes problems with your previewtool? this build used the latest libraries you have prepared.

**Comment by KimihideIiizumi** [comment]
I changed the PC I am using and tried it, and for some reason the file size issue was resolved, thank you.

However, I still don't understand the issue of the screen not changing from the splash screen.

Looking at your screenshot, it seems to work fine in your app, but in the file I gave you, it doesn't seem to change from the splash screen.

**Comment by KimihideIiizumi** [comment]
This problem was fixed when CocosCreator was updated from 3.6.1 to 3.8.1.

Thanks for your generous support.
